In [3]:
!pip install numpy pandas scikit-learn matplotlib seaborn
!pip install torch transformers datasets gradio
!pip install nltk

Requirement already satisfied: numpy in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (2.0.1)
Requirement already satisfied: pandas in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (2.3.2)
Requirement already satisfied: scikit-learn in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (1.7.1)
Requirement already satisfied: matplotlib in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (3.10.6)
Requirement already satisfied: seaborn in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: scipy>=1.8.0 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from matplotlib) (4.59.2)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from matplotlib) (3.2.0)
Requirement already satisfied: six>=1.5 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Collecting torch
  Using cached torch-2.11.0-cp310-cp310-win_amd64.whl.metadata (29 kB)
Collecting transformers
  Using cached transformers-5.5.3-py3-none-any.whl.metadata (32 kB)
Collecting datasets
  Using cached datasets-4.8.4-py3-none-any.whl.metadata (19 kB)
Collecting gradio
  Using cached gradio-6.11.0-py3-none-any.whl.metadata (17 kB)
Collecting filelock (from torch)
  Using cached filelock-3.25.2-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools<82 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from torch) (78.1.1)
Requirement already satisfied: sympy>=1.13.3 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from torch) (1.14.0)
Collecting networkx>=2.5.1 (from torch)
  Using cached networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: jinja2 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from torch) (3.1.6)
Collecting fsspec>=0.8.5 (from torch)
  Using cached fsspec-2026.3.0-py3-none-any.whl.metadata (10 kB)
Collecting huggingface-hub<2.0,>=1.5.0 (from transformers)
  Using cached huggingface_hub-1.10.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy>=1.17 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from transformers) (2.0.1)
Requirement already satisfied: packaging>=20.0 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from transformers) (2026.1.15)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers)
  Using cached tokenizers-0.22.2-cp39-abi3-win_amd64.whl.metadata (7.4 kB)
Collecting typer (from transformers)
  Using cached typer-0.24.1-py3-none-any.whl.metadata (16 kB)
Collecting safetensors>=0.4.3 (from transformers)
  Using cached safetensors-0.7.0-cp38-abi3-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: tqdm>=4.27 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from transformers) (4.67.1)
Collecting hf-xet<2.0.0,>=1.4.3 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached hf_xet-1.4.3-cp37-abi3-win_amd64.whl.metadata (4.9 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: anyio in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.11.0)
Requirement already satisfied: certifi in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2025.10.5)
Requirement already satisfied: httpcore==1.* in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.10)
Requirement already satisfied: h11>=0.16 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Collecting pyarrow>=21.0.0 (from datasets)
  Using cached pyarrow-23.0.1-cp310-cp310-win_amd64.whl.metadata (3.1 kB)
Collecting dill<0.4.2,>=0.3.0 (from datasets)
  Using cached dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from datasets) (2.3.2)
Requirement already satisfied: requests>=2.32.2 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from datasets) (2.32.5)
Requirement already satisfied: xxhash in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from datasets) (3.6.0)
Collecting multiprocess<0.70.20 (from datasets)
  Using cached multiprocess-0.70.19-py310-none-any.whl.metadata (7.5 kB)
Collecting fsspec>=0.8.5 (from torch)
  Using cached fsspec-2026.2.0-py3-none-any.whl.metadata (10 kB)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached aiohttp-3.13.5-cp310-cp310-win_amd64.whl.metadata (8.4 kB)
Collecting aiofiles<25.0,>=22.0 (from gradio)
  Using cached aiofiles-24.1.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: brotli>=1.1.0 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from gradio) (1.2.0)
Collecting fastapi<1.0,>=0.115.2 (from gradio)
  Using cached fastapi-0.135.3-py3-none-any.whl.metadata (28 kB)
Collecting ffmpy (from gradio)
  Using cached ffmpy-1.0.0-py3-none-any.whl.metadata (3.0 kB)
Collecting gradio-client==2.4.0 (from gradio)
  Using cached gradio_client-2.4.0-py3-none-any.whl.metadata (7.1 kB)
Collecting groovy~=0.1 (from gradio)
  Using cached groovy-0.1.2-py3-none-any.whl.metadata (6.1 kB)
Collecting hf-gradio<1.0,>=0.3.0 (from gradio)
  Using cached hf_gradio-0.3.0-py3-none-any.whl.metadata (404 bytes)
Requirement already satisfied: markupsafe<4.0,>=2.0 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from gradio) (3.0.3)
Collecting orjson~=3.0 (from gradio)
  Using cached orjson-3.11.8-cp310-cp310-win_amd64.whl.metadata (43 kB)
Requirement already satisfied: pillow<13.0,>=8.0 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from gradio) (11.3.0)
Collecting pydantic<=3.0,>=2.0 (from gradio)
  Using cached pydantic-2.12.5-py3-none-any.whl.metadata (90 kB)
Requirement already satisfied: pydub in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from gradio) (0.25.1)
Collecting python-multipart>=0.0.18 (from gradio)
  Using cached python_multipart-0.0.24-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: pytz>=2017.2 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from gradio) (2025.2)
Collecting safehttpx<0.2.0,>=0.1.7 (from gradio)
  Using cached safehttpx-0.1.7-py3-none-any.whl.metadata (4.2 kB)
Collecting semantic-version~=2.0 (from gradio)
  Using cached semantic_version-2.10.0-py2.py3-none-any.whl.metadata (9.7 kB)
Collecting starlette<2.0,>=0.40.0 (from gradio)
  Using cached starlette-1.0.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: tomlkit<0.14.0,>=0.12.0 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from gradio) (0.13.3)
Collecting uvicorn>=0.14.0 (from gradio)
  Using cached uvicorn-0.44.0-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.2.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.1)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from fastapi<1.0,>=0.115.2->gradio) (0.4.2)
Collecting annotated-doc>=0.0.2 (from fastapi<1.0,>=0.115.2->gradio)
  Using cached annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from pandas->datasets) (2025.2)
Collecting annotated-types>=0.6.0 (from pydantic<=3.0,>=2.0->gradio)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.41.5 (from pydantic<=3.0,>=2.0->gradio)
  Using cached pydantic_core-2.41.5-cp310-cp310-win_amd64.whl.metadata (7.4 kB)
Requirement already satisfied: click>=8.2.1 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from typer->transformers) (8.3.1)
Collecting shellingham>=1.3.0 (from typer->transformers)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: rich>=12.3.0 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from typer->transformers) (14.1.0)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Collecting async-timeout<6.0,>=4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached async_timeout-5.0.1-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: attrs>=17.3.0 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (25.4.0)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached frozenlist-1.8.0-cp310-cp310-win_amd64.whl.metadata (21 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached multidict-6.7.1-cp310-cp310-win_amd64.whl.metadata (5.5 kB)
Collecting propcache>=0.2.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached propcache-0.4.1-cp310-cp310-win_amd64.whl.metadata (14 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached yarl-1.23.0-cp310-cp310-win_amd64.whl.metadata (82 kB)
Requirement already satisfied: colorama in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from click>=8.2.1->typer->transformers) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from requests>=2.32.2->datasets) (3.4.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from rich>=12.3.0->typer->transformers) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\arshi\anaconda3\envs\venv\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Using cached torch-2.11.0-cp310-cp310-win_amd64.whl (114.5 MB)
Using cached transformers-5.5.3-py3-none-any.whl (10.2 MB)
Using cached huggingface_hub-1.10.1-py3-none-any.whl (642 kB)
Using cached hf_xet-1.4.3-cp37-abi3-win_amd64.whl (3.7 MB)
Using cached tokenizers-0.22.2-cp39-abi3-win_amd64.whl (2.7 MB)
Using cached datasets-4.8.4-py3-none-any.whl (526 kB)
Using cached dill-0.4.1-py3-none-any.whl (120 kB)
Using cached fsspec-2026.2.0-py3-none-any.whl (202 kB)
Using cached multiprocess-0.70.19-py310-none-any.whl (134 kB)
Using cached gradio-6.11.0-py3-none-any.whl (36.8 MB)
Using cached gradio_client-2.4.0-py3-none-any.whl (59 kB)
Using cached aiofiles-24.1.0-py3-none-any.whl (15 kB)
Using cached fastapi-0.135.3-py3-none-any.whl (117 kB)
Using cached groovy-0.1.2-py3-none-any.whl (14 kB)
Using cached hf_gradio-0.3.0-py3-none-any.whl (4.2 kB)
Using cached orjson-3.11.8-cp310-cp310-win_amd64.whl (127 kB)
Using cached pydantic-2.12.5-py3-none-any.whl (463 kB)
Using cached pydantic_core-2.41.5-cp310-cp310-win_amd64.whl (2.0 MB)
Using cached safehttpx-0.1.7-py3-none-any.whl (9.0 kB)
Using cached semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
Using cached starlette-1.0.0-py3-none-any.whl (72 kB)
Using cached typer-0.24.1-py3-none-any.whl (56 kB)
Using cached aiohttp-3.13.5-cp310-cp310-win_amd64.whl (462 kB)
Using cached async_timeout-5.0.1-py3-none-any.whl (6.2 kB)
Using cached multidict-6.7.1-cp310-cp310-win_amd64.whl (46 kB)
Using cached yarl-1.23.0-cp310-cp310-win_amd64.whl (87 kB)
Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Using cached aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Using cached annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Using cached filelock-3.25.2-py3-none-any.whl (26 kB)
Using cached frozenlist-1.8.0-cp310-cp310-win_amd64.whl (43 kB)
Using cached networkx-3.4.2-py3-none-any.whl (1.7 MB)
Using cached propcache-0.4.1-cp310-cp310-win_amd64.whl (41 kB)
Using cached pyarrow-23.0.1-cp310-cp310-win_amd64.whl (27.5 MB)
Using cached python_multipart-0.0.24-py3-none-any.whl (24 kB)
Using cached safetensors-0.7.0-cp38-abi3-win_amd64.whl (341 kB)
Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Using cached uvicorn-0.44.0-py3-none-any.whl (69 kB)
Using cached ffmpy-1.0.0-py3-none-any.whl (5.6 kB)
Installing collected packages: shellingham, semantic-version, safetensors, python-multipart, pydantic-core, pyarrow, propcache, orjson, networkx, multidict, hf-xet, groovy, fsspec, frozenlist, filelock, ffmpy, dill, async-timeout, annotated-types, annotated-doc, aiohappyeyeballs, aiofiles, yarl, uvicorn, torch, starlette, pydantic, multiprocess, aiosignal, typer, safehttpx, fastapi, aiohttp, huggingface-hub, tokenizers, gradio-client, datasets, transformers, hf-gradio, gradio

   -- -------------------------------------  2/40 [safetensors]
   ---- -----------------------------------  4/40 [pydantic-core]
   ----- ----------------------------------  5/40 [pyarrow]
   ----- ----------------------------------  5/40 [pyarrow]
   ----- ----------------------------------  5/40 [pyarrow]
   ----- ----------------------------------  5/40 [pyarrow]
   ----- ----------------------------------  5/40 [pyarrow]
   ----- ----------------------------------  5/40 [pyarrow]
   ----- ----------------------------------  5/40 [pyarrow]
   ----- ----------------------------------  5/40 [pyarrow]
   ----- ----------------------------------  5/40 [pyarrow]
   ----- ----------------------------------  5/40 [pyarrow]
   ----- ----------------------------------  5/40 [pyarrow]
   ----- ----------------------------------  5/40 [pyarrow]
   ----- ----------------------------------  5/40 [pyarrow]
   ----- ----------------------------------  5/40 [pyarrow]
   ----- ----------------------------------  5/40 [pyarrow]
   ------- --------------------------------  7/40 [orjson]
   -------- -------------------------------  8/40 [networkx]
   -------- -------------------------------  8/40 [networkx]
   -------- -------------------------------  8/40 [networkx]
   -------- -------------------------------  8/40 [networkx]
   -------- -------------------------------  8/40 [networkx]
   -------- -------------------------------  8/40 [networkx]
   -------- -------------------------------  8/40 [networkx]
   -------- -------------------------------  8/40 [networkx]
   -------- -------------------------------  8/40 [networkx]
   -------- -------------------------------  8/40 [networkx]
   -------- -------------------------------  8/40 [networkx]
   -------- -------------------------------  8/40 [networkx]
   -------- -------------------------------  8/40 [networkx]
   -------- -------------------------------  8/40 [networkx]
   -------- -------------------------------  8/40 [networkx]
   -------- -------------------------------  8/40 [networkx]
   -------- -------------------------------  8/40 [networkx]
   -------- -------------------------------  8/40 [networkx]
   -------- -------------------------------  8/40 [networkx]
   -------- -------------------------------  8/40 [networkx]
   -------- -------------------------------  8/40 [networkx]
   -------- -------------------------------  8/40 [networkx]
   -------- -------------------------------  8/40 [networkx]
   -------- -------------------------------  8/40 [networkx]
   -------- -------------------------------  8/40 [networkx]
   ---------- ----------------------------- 10/40 [hf-xet]
   ------------ --------------------------- 12/40 [fsspec]
   ------------ --------------------------- 12/40 [fsspec]
   ------------ --------------------------- 12/40 [fsspec]
   ------------ --------------------------- 12/40 [fsspec]
   ------------ --------------------------- 12/40 [fsspec]
   ------------ --------------------------- 12/40 [fsspec]
   ------------ --------------------------- 12/40 [fsspec]
   -------------- ------------------------- 14/40 [filelock]
   ---------------- ----------------------- 16/40 [dill]
   ---------------- ----------------------- 16/40 [dill]
   ---------------- ----------------------- 16/40 [dill]
   ------------------ --------------------- 18/40 [annotated-types]
   ------------------- -------------------- 19/40 [annotated-doc]
   -------------------- ------------------- 20/40 [aiohappyeyeballs]
   ---------------------- ----------------- 22/40 [yarl]
   ----------------------- ---------------- 23/40 [uvicorn]
   ------------------------ --------------- 24/40 [torch]
   ------------------------ --------------- 24/40 [torch]
   ------------------------ --------------- 24/40 [torch]

In [2]:
import pandas as pd
import numpy as np
import re
import pickle
from collections import Counter
from sklearn.model_selection import train_test_split

In [4]:
import re, math, pickle, os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset, Dataset
from torch.optim import AdamW
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, f1_score, confusion_matrix
from transformers import AutoTokenizer, AutoModelForSequenceClassification, get_linear_schedule_with_warmup

In [5]:

import nltk

from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
import torch
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\arshi/nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

In [9]:
df = pd.read_csv("data/train-balanced-sarcasm.csv") 

df = df.rename(columns={
    "comment": "text",
    "label": "label"
})

df = df[['text', 'label']]
df.dropna(inplace=True)

df.head()

                                                text  label
0                                         NC and NH.      0
1  You do know west teams play against west teams...      0
2  They were underdogs earlier today, but since G...      0
3  This meme isn't funny none of the "new york ni...      0
4                    I could use one of those tools.      0

In [10]:
stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = text.lower()
    text = re.sub(r'http\S+', '', text)        
    text = re.sub(r'[^a-zA-Z\s]', '', text)    
    words = text.split()
    words = [w for w in words if w not in stop_words]
    return " ".join(words)

df['clean_text'] = df['text'].apply(clean_text)
df.head()

,text,label,clean_text
0,NC and NH.,0,nc nh
1,You do know west teams play against west teams...,0,know west teams play west teams east teams right
2,"They were underdogs earlier today, but since G...",0,underdogs earlier today since gronks announcem...
3,"This meme isn't funny none of the ""new york ni...",0,meme isnt funny none new york nigga ones
4,I could use one of those tools.,0,could use one tools

In [11]:
train_texts, val_texts, train_labels, val_labels = train_test_split(
    df['clean_text'],
    df['label'],
    test_size=0.1,
    random_state=42
)

In [12]:
from collections import Counter

def tokenize(text):
    return text.split()

all_tokens = []
for text in train_texts:
    all_tokens.extend(tokenize(text))

vocab = Counter(all_tokens)
vocab = {word: i+1 for i, (word, _) in enumerate(vocab.items())}

In [13]:
def encode(text, vocab):
    return [vocab.get(word, 0) for word in text.split()]

train_sequences = [encode(text, vocab) for text in train_texts]
val_sequences = [encode(text, vocab) for text in val_texts]

In [14]:
from torch.nn.utils.rnn import pad_sequence

train_sequences = [torch.tensor(seq) for seq in train_sequences]
val_sequences = [torch.tensor(seq) for seq in val_sequences]

train_padded = pad_sequence(train_sequences, batch_first=True)
val_padded = pad_sequence(val_sequences, batch_first=True)

In [15]:
class TextDataset(Dataset):
    def __init__(self, texts, labels):
        self.texts = texts
        self.labels = torch.tensor(labels.values)

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return self.texts[idx], self.labels[idx]

In [16]:
train_dataset = TextDataset(train_padded, train_labels)
val_dataset = TextDataset(val_padded, val_labels)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=32)

In [17]:
class LSTMModel(nn.Module):
    def __init__(self, vocab_size, embed_dim=128, hidden_dim=128):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size+1, embed_dim)
        self.lstm = nn.LSTM(embed_dim, hidden_dim, batch_first=True)
        self.fc = nn.Linear(hidden_dim, 2)

    def forward(self, x):
        x = self.embedding(x)
        _, (hidden, _) = self.lstm(x)
        out = self.fc(hidden[-1])
        return out

In [18]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = LSTMModel(len(vocab)).to(device)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [19]:
for epoch in range(5):
    model.train()
    total_loss = 0

    for x, y in train_loader:
        x, y = x.to(device), y.to(device)

        optimizer.zero_grad()
        outputs = model(x)
        loss = criterion(outputs, y)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}")

KeyboardInterrupt: