In [1]:
print("hello")

hello

In [3]:
import pandas as pd

In [ ]:
train_df = pd.read_csv("twitter_training.csv")

In [66]:
valid_df = pd.read_csv("twitter_validation.csv")

In [44]:
train_df.head()

   Index        Title Sentiment                           text
0   2401  Borderlands  Positive         [coming, border, kill]
1   2401  Borderlands  Positive    [getting, borderland, kill]
2   2401  Borderlands  Positive   [coming, borderland, murder]
3   2401  Borderlands  Positive  [getting, borderland, murder]
4   2401  Borderlands  Positive  [getting, borderland, murder]

In [47]:
train_df.Sentiment.value_counts()

Sentiment
Negative      22542
Positive      20831
Neutral       18318
Irrelevant    12990
Name: count, dtype: int64

In [8]:
train_df.columns

Index(['2401', 'Borderlands', 'Positive',
       'im getting on borderlands and i will murder you all ,'],
      dtype='str')

In [58]:
train_df.columns = ["Index","Title","Sentiment","text"]

valid_df.columns = ["Index","Title","Sentiment","text"]

In [12]:
train_df.head()

,Index,Title,Sentiment,text
0,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
1,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
2,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
3,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
4,2401,Borderlands,Positive,im getting into borderlands and i can murder y...

In [59]:
valid_df.head()

,Index,Title,Sentiment,text
0,352,Amazon,Neutral,BBC News - Amazon boss Jeff Bezos rejects clai...
1,8312,Microsoft,Negative,@Microsoft Why do I pay for WORD when it funct...
2,4371,CS-GO,Negative,"CSGO matchmaking is so full of closet hacking,..."
3,4433,Google,Neutral,Now the President is slapping Americans in the...
4,6273,FIFA,Negative,Hi @EAHelp I’ve had Madeleine McCann in my cel...

In [13]:
valid_df.head()

,Index,Title,Sentiment,text
0,352,Amazon,Neutral,BBC News - Amazon boss Jeff Bezos rejects clai...
1,8312,Microsoft,Negative,@Microsoft Why do I pay for WORD when it funct...
2,4371,CS-GO,Negative,"CSGO matchmaking is so full of closet hacking,..."
3,4433,Google,Neutral,Now the President is slapping Americans in the...
4,6273,FIFA,Negative,Hi @EAHelp I’ve had Madeleine McCann in my cel...

In [15]:
train_df["Title"].unique()

<StringArray>
[                      'Borderlands',         'CallOfDutyBlackopsColdWar',
                            'Amazon',                         'Overwatch',
                     'Xbox(Xseries)',                             'NBA2K',
                             'Dota2',                 'PlayStation5(PS5)',
                      'WorldOfCraft',                             'CS-GO',
                            'Google',                    'AssassinsCreed',
                       'ApexLegends',                   'LeagueOfLegends',
                          'Fortnite',                         'Microsoft',
                       'Hearthstone',                       'Battlefield',
 'PlayerUnknownsBattlegrounds(PUBG)',                           'Verizon',
                         'HomeDepot',                              'FIFA',
            'RedDeadRedemption(RDR)',                        'CallOfDuty',
              'TomClancysRainbowSix',                          'Facebook',
               'GrandTheftAuto(GTA)',                         'MaddenNFL',
                   'johnson&johnson',                     'Cyberpunk2077',
              'TomClancysGhostRecon',                            'Nvidia']
Length: 32, dtype: str

In [16]:
valid_df["text"]

0      BBC News - Amazon boss Jeff Bezos rejects clai...
1      @Microsoft Why do I pay for WORD when it funct...
2      CSGO matchmaking is so full of closet hacking,...
3      Now the President is slapping Americans in the...
4      Hi @EAHelp I’ve had Madeleine McCann in my cel...
                             ...
994    ⭐️ Toronto is the arts and culture capital of ...
995    tHIS IS ACTUALLY A GOOD MOVE TOT BRING MORE VI...
996    Today sucked so it’s time to drink wine n play...
997    Bought a fraction of Microsoft today. Small wins.
998    Johnson & Johnson to stop selling talc baby po...
Name: text, Length: 999, dtype: str

In [17]:
import nltk

In [26]:
import re
import string
nltk.download("punkt_tab")
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
lemma = WordNetLemmatizer()
from nltk.corpus import stopwords
nltk.download("stopwords")

sw = set(stopwords.words("english"))

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Asus\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Asus\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Asus\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
def preprocess(sentence):
    if not isinstance(sentence, str):
        return []

    sentence = sentence.strip()
    if sentence == "":
        return []
    if sentence.startswith(".."):
        if not any(c.isalpha() for c in sentence):
            return []
        sentence = sentence.lstrip(". ").strip()

    sentence = sentence.lower()
    print(sentence)

    sentence = re.sub(r"http\S+|www\S+", "", sentence)
    sentence = re.sub(r"\d+", "", sentence)
    sentence = sentence.translate(str.maketrans("", "", string.punctuation))

    tokens = nltk.word_tokenize(sentence)
    tokens = [t for t in tokens if t not in sw]
    tokens = [t for t in tokens if len(t) > 2]
    tokens = [lemma.lemmatize(t) for t in tokens]

    return tokens

In [57]:
valid_df.head()

,3364,Facebook,Irrelevant,"I mentioned on Facebook that I was struggling for motivation to go for a run the other day, which has been translated by Tom’s great auntie as ‘Hayley can’t get out of bed’ and told to his grandma, who now thinks I’m a lazy, terrible person 🤣"
0,352,Amazon,Neutral,BBC News - Amazon boss Jeff Bezos rejects clai...
1,8312,Microsoft,Negative,@Microsoft Why do I pay for WORD when it funct...
2,4371,CS-GO,Negative,"CSGO matchmaking is so full of closet hacking,..."
3,4433,Google,Neutral,Now the President is slapping Americans in the...
4,6273,FIFA,Negative,Hi @EAHelp I’ve had Madeleine McCann in my cel...

In [ ]:
train_df['text'] = train_df['text'].map(preprocess)

i am coming to the borders and i will kill you all,
im getting on borderlands and i will kill you all,
im coming on borderlands and i will murder you all,
im getting on borderlands 2 and i will murder you me all,
im getting into borderlands and i can murder you all,
so i spent a few hours making something for fun. . . if you don't know i am a huge @borderlands fan and maya is one of my favorite characters. so i decided to make myself a wallpaper for my pc. . here is the original image versus the creation i made :) enjoy! pic.twitter.com/mlsi5wf9jg
so i spent a couple of hours doing something for fun... if you don't know that i'm a huge @ borderlands fan and maya is one of my favorite characters, i decided to make a wallpaper for my pc.. here's the original picture compared to the creation i made:) have fun! pic.twitter.com / mlsi5wf9jg
so i spent a few hours doing something for fun... if you don't know i'm a huge @ borderlands fan and maya is one of my favorite characters.
so i spent a few hours making something for fun. . . if you don't know i am a huge rhandlerr fan and maya is one of my favorite characters. so i decided to make myself a wallpaper for my pc. . here is the original image versus the creation i made :) enjoy! pic.twitter.com/mlsi5wf9jg
2010 so i spent a few hours making something for fun. . . if you don't know i am a huge rhandlerr fan and maya is one of my favorite characters. so i decided to make myself a wallpaper for my pc. . here is the original image versus the creation i made :) enjoy! pic.twitter.com/mlsi5wf9jg
was
rock-hard la varlope, rare & powerful, handsome jackpot, borderlands 3 (xbox) dlvr.it/rmtrgf
rock-hard la varlope, rare & powerful, handsome jackpot, borderlands 3 (xbox) dlvr.it / rmtrgf
rock-hard la varlope, rare & powerful, handsome jackpot, borderlands 3 (xbox) dfr.it / rmtrgf
rock-hard la vita, rare but powerful, handsome jackpot, borderlands 1 (xbox) dlvr.it/rmtrgf
live rock - hard music la la varlope, rare & the powerful, live handsome i jackpot, borderlands 3 ( sega xbox ) dlvr. from it / e rmtrgf
i-hard like me, rare london de, handsome 2011, borderlands 3 (xbox) dlvr.it/rmtrgf
that was the first borderlands session in a long time where i actually had a really satisfying combat experience. i got some really good kills
this was the first borderlands session in a long time where i actually had a really satisfying fighting experience. i got some really good kills
that was the first borderlands session in a long time where i actually had a really satisfying combat experience. i got some really good kills
that was the first borderlands session in a long time where i actually enjoyed a really satisfying combat experience. i got some rather good kills
that i was the first real borderlands session in a nice long wait time where i actually had a really satisfying combat experience. and i got some really good kills
that was the first borderlands session in a hot row where i actually had a really bad combat experience. i did some really good kills
the biggest dissappoinment in my life came out a year ago fuck borderlands 3
the biggest disappointment of my life came a year ago.
the biggest disappointment of my life came a year ago.
the biggest dissappoinment in my life coming out a year ago fuck borderlands 3
for the biggest male dissappoinment in my life came hanging out a year time ago fuck borderlands 3
the biggest dissappoinment in my life came back last year ago fuck borderlands last
we finished borderlands 3 finally yas! thank you for hanging out everyone! it was fun. i will try to stream tomorrow but if not i might so some irl streams while awayu. we shall see. thank you so much for the raids @mompou_mumpow @megamagwitch and @kfdmitch.
we finally finally find borderlands 3 yes! thank you all for hanging out! it was fun. i'll try to stream tomorrow, but if not, maybe some irl streams. we'll see. thanks for the raids @ mompou _ mumpow @ megamagwitch and @ kfdmitch.
thank you for hanging up everyone! it was fun. i'll try to get a haircut tomorrow, but if it wasn't for me, some irl streams would still be in hawaii. we'll see. thank you so much for the @ mompou _ mumpow @ megamagwife and @ fendmitch raids.
we finished borderlands 3 update yas! thank you for hanging out guys! it was fun. i will try to stream and even if not i might so some irl streams while awayu. we shall go. thank you so much for the raids @mompou_mumpow @megamagwitch and hope.
we finished borderlands 3 and finally yas! thank you everyone for hanging out everyone! it was fun. i will try to make stream tomorrow but if not i might make so some irl streams while awayu. 10 we never shall see. thank you both so... much for the raids @mompou_mumpow or @megamagwitch and 4 @kfdmitch.
we finished borderlands 3 finally yas! hey you for hanging out so! it was fun. i will try that stream tomorrow and if not i might use some irl streams from awayu. we shall see. thank you so much how many raids @mompou_mumpow did and their.
man gearbox really needs to fix this dissapointing drops in the new borderlands 3 dlc cant be fine to farm bosses on mayhem 10 to get 1 legendary drop while anywhere else i get 6-10 drops. . really sucks alot
man gearbox really needs to fix these disappointing drops in the new borderlands 3 dlc for farm bosses on mayhem 10 to get a legendary drop, while i get 6-10 drops elsewhere.
man gearbox really needs to fix this disssapointing drops in the new borderlands 3 dlc cant be fine to farm bosses on mayhem 10 to get 1 legendary drop while elsewhere i get 6-10 drops... really sucks alot
man bethesda really needs to fix this dissapointing drops and the new borderlands 3 it cant be fine to farm bosses on mayhem 10 to get 1 legendary drop while anywhere else i get 6-10 drops.. really sucks...
man gearbox really needs to fix this dissapointing drops in the completely new borderlands 3 days dlc i cant e be fine having to be farm bosses on mayhem 10 to e get 1 legendary foot drop while anywhere else i get 6 - 10 drops.. it really sucks to alot
<unk> gearbox really time to fix this 10 drops in the new borderlands 3 dlc or be fine to force bosses on mayhem 10 to get a legendary drop while everyone else i get 6-10 drops.. really needs alot
check out this epic streamer!.
check out this epic streamer!.
watch this epic striptease!.
check out our epic streamer!.
check out this big epic streamer!.
check<unk> this epic streamer!.
blaming sight for tardiness! a little bit of borderlands. i got called in early for work tomorrow so i can't make up time. sorry my loves .  twitch.tv/punnisenpai
a bit of borderland. i was called to work tomorrow morning, so i can't catch up. sorry, my love. twitch.tv / punnisenpai
guilty of sobriety! a bit of a borderline. i was called to work early tomorrow, so i can't catch up.
blaming sight for tardiness! a little bit of borderlands. i got called in early for work tomorrow so i can't make up time. sorry my loves .  twitch.tv/punnisenpai
for blaming sight for tardiness! a little bit of borderlands. i got called in early for work tomorrow so i can't make up time. sorry my loves .  twitch.tv/punnisenpai
all
why does like every man in borderlands have slicked back hair haven’t you heard of bangs you stupid assholes
why, like every man in border countries, have you not heard of bangs, you stupid assholes?
why, like everyone else in the border countries, have your hair fallen off, have you not heard that you are stupid aliens?
why does like<unk> man in borderlands have slicked back hair or you heard of bangs you stupid assholes
why beth does like every man in borderlands have she slicked that back hair haven ’ t you heard enough of gray bangs you stupid assholes
why does practically every man in france have slicked back hair haven’t you heard of bangs the greedy assholes
. . [
what
going to finish up borderlands 2 today. i've got some new commands set up and am looking forward to a good stream! starting in about am hour!
i will finish borderlands 2 today. i have some new commands set up and am looking forward to a good stream! start in about an hour!
i'm going to finish borderlands 2 today. i have some new commands installed and i'm looking forward to a good stream!
going to finish up borderlands 2 today. i've got some new events set up and am look forward to a good stream! starting in about 20 hour!
going to finish finish cleaning up borderlands 2 today. i've just got her some new commands set all up and am looking forward it to a good stream! starting in about am hour!
going to finish up volume 2 today. i've got some awesome server set up and is looking forward to a good stream! starting in about am hour!
imma probably play some borderlands tps in a bit . that'll be fun
imma is probably playing a bit of borderland tps. that will be fun.
imma will probably play some border tps in a bit. it's going to be fun
imma probably play live borderlands tps in a bit. that'll be fun
for imma probably play some borderlands tps in a bit. that'yer ll be a fun
imma probably got some video tps in a bit. that'll make fun
one of our own @profzeroo is live w/ @borderlands 3‼.  .  . . catch him here: buff.ly/2wmmip5 . . say "streamer shouts" in chat for a chance to be in a coming. @streamer_shouts shout out. . .
one of our own @ profzeroo is live w / @ borderlands 3.... catch him here: buff.ly / 2wmmip5.. say "streamer shouts" in chat for a chance to be in an upcoming one. @ streamer _ shouts shout out...
one of our own @ profzero - live w / @ borderlands 3.... catch him here: buff.ly / 2wmmip5... say "stream shouts" in chat for a chat for a chance to be in a coming. @ stream _ shouts shout out....
one of our own @profzeroo is live >/ @borderlands 3‼. . !. catch him here: buff.ly/2wmmip5 p. say some shouts" in chat – a chance to be in a coming. also shout out...
one of our shows own @profzeroo is live via w / at @borderlands 3 and [unk].... catch him here : the buff. ly / to 2wmmip5.. to say " streamer shouts " in chat for a chance to officially be in a series coming. @streamer_shouts 1 shout out...
one of its own movies is live w/ @profzeroo 3!!.... catch him from: buff.ly/2wmmip5.. for "streamer shouts" in invitation or a chance to be out a coming. all 3 invites...
fuck yessssssss .
fick yessssss.
fuck yessssssss.
fuck yessssssss<unk>
a fuck... yessssssss.
fuck you.
i hate that this easy mayhem modifier event on mayhem won’t last forever. this is the most fun i’ve had in the game since they added them horrible modifiers. @borderlands please give me the option to play mayhem 10 but turn the modifiers off pls
i hate that this simple chaos modifier event on chaos won't last forever. that's the most fun i've had in the game since they added terrible modifiers. @ borderlands please give me the option to play chaos 10 but turn off the modifiers.
i hate that this easy mayhem modifier event on mayhem won't last forever. this is the most fun i've had in the game since they added them horrible modifiers. @ borderlands please give me the option to play mayhem 10 but turn the modifiers off pls
i hate saying this easy day 9 event on mayhem won’t last forever. this is the most fun i’ve had in the game since they added them horrible modifiers. @borderlands please give me some ability to play mayhem 10 but turn the modifiers off pls
i hate thinking that this easy mayhem modifier event on total mayhem won ’ t last forever. this is the absolutely most ridiculous fun experience i ’ ve had in the game almost since... they added them horrible modifiers. @borderlands please do give me the option option to a play mayhem 10 but turn the modifiers off pls
i hate that this easy horrible modifier event on game 10 last forever. that is the best fun i’ve taken in the past until they added them horrible modifiers. @borderlands please send me the option to play mayhem 10 but turn the modifiers for pls
grounded almost looked pretty cool even despite the borderlands tier unfunny writing until it became yet another survival crafting game. i really can’t wait for this shitty trend to die
grounded looked cool despite the borderline unfunny writing, until it became another survival crafting game. i really can't wait for this crappy trend to die.
grosskreutz looked pretty cool, even despite the unfunny spelling, until it turned into another survival game. i really can't wait for this crap trend to die
grounded almost looked pretty cool here despite the borderlands tier unfunny writing until it became yet an survival crafting game. i really can’t wait for this shitty mod to die
deep grounded almost looked pretty cool even despite the borderlands fifth tier unfunny writing format until ultimately it became yet another survival crafting mobile game. i really can ’ t wait for this shitty trend starting to... die
grounded almost was pretty cool even despite the top tier unfunny writing until we became yet another annoying crafting game. i seriously can’t wait on this shitty trend to die
appreciate the (sonic) concepts / praxis valenzuela and landa-posas thread together in this talk: multimodal listening, soundwalks, borderlands frameworks, participatory action research, and testimonios. . . so many thoughtful and resonant intersections here.. .
appreciate the (sound) concepts / practices that valenzuela and landa-posas combine in this lecture: multimodal listening, soundwalks, borderland frameworks, participatory action research and testimonies... so many thoughtful and resonant intersections here...
evaluate the (sound) concepts / concepts of valensela and landa pozas together in this conversation: multimodal listening, walks, border areas, joint action studies, etc. so many amazing and resonant intersections here...
appreciate the (sonic) concepts / praxis valenzuela and moreno-posas have together in this talk: multimodal listening, soundwalks, borderlands recordings, participatory field research, and testimonios.... so many thoughtful and resonant intersections here.. :-)
appreciate by the ( sonic ) electronic concepts / praxis valenzuela and landa - posas do thread together together in creating this talk : multimodal visual listening, digital soundwalks, borderlands frameworks, participatory action research, interviews and testimonios... so many thoughtful thoughts and resonant intersections reflected here...
appreciate the (sonic) conversations / actions klein and landa-posas brought together in our talk: multimodal experiences, soundwalks, ethical frameworks, participatory action practices, and testimonios... so many provocative and resonant intersections today...
@borderlands how do i submit a complaint? your ceo isn't paying his staff their bonuses.
@ borderlands, how can i file a complaint? your ceo doesn't pay his employees their bonuses.
@ borderlands how to file a complaint? your ceo doesn't pay his employees bonuses.
@borderlands how did i submit a complaint? your ceo isn't paying his competitors their bonuses.
@borderlands how do suppose i submit a complaint? your ceo isn'ain t even paying his entire staff their bonuses.
now how do i submit any complaint? your ceo isn't offering his staff their bonuses.
all the borderlands are fuckin trash
all the borderlands are damn rubbish
all the borderlands are fucking thrash
all the borderlands shit fuckin trash
35 all the borderlands are fuckin trash
all the borderlands are fuckin stupid
finally played through borderlands 3. the actual game play is great. almost all guns feel fun, and i never once felt like i needed to grind. that story on the other hand.... all i will say is that i'm very much so looking forward to the eventual cutscene skip :)
finally played by borderlands 3. the actual game is great. almost all weapons feel funny, and i never felt like i had to grind. on the other hand... all i will say is that i am very much looking forward to the eventual sequence skip:)
this story on the other hand.... all i will say is that i'm looking forward to an occasional slip:)
finally played through borderlands 3. the open game play is great. almost all guns feel fun, and i never once felt like i needed to grind. the story on to another hand.... all i will say is that i'm very much so looking forward to its eventual cutscene skip :)
finally played through borderlands 3. the actual game i play is great. almost all guns feel fun, and yet i never once felt much like someone i seriously needed to grind. that pretty story on the other side hand.... all i will say is that i'm very damn much so forward looking forward to the eventual endless cutscene skip : )
finally played through borderlands 5. the actual game play is great. almost all guns were fun, and i never once felt sure i needed to grind. that story is the other hand.... but i will say now oh yes'm very much so looking forward to the extended cutscene skip :)
loving these new @ghostlifestyle cans!! anyone else drink ghost?. .. .. . .
i love these new @ ghostlifestyle cans!! everyone else drinks ghost?....
love these new @ ghostlive cans!! does anyone else drink ghost?..
loving these new @ghostlifestyle cans!! anyone else drink ghost?......
loving back these three new @ghostlifestyle cans!! by anyone else else drink ghost?.......
do these new @ghostlifestyle<unk> they want drink ghost?.......
come meet one of the lovely gaming goddesses .
meet one of the lovely gambling goddesses.
come meet one of the beautiful gods of gambling.
come to one of the lovely gaming goddesses.
16 come meet one of... the lovely gaming goddesses.
come meet one of the lovely green goddesses.
how the hell are we into halloween month already?! .
how the hell are we already into halloween month?!.
how the hell are we already in halloween month?!.
how the hell are march into halloween month already?!.
how the hell are pulling we into halloween month starting already?!.
in the hell are we into halloween month already?!.
"what a bitch!"
"what a slut!"
"what a bitch!"
"what terrible bitch!"
"... what a bitch! "
"what a miracle!"
ok i am loving this (also playing bombs over baghdad in anything gets me hype)  very borderlands like and the concept is a1!
ok i'm loving this (also playing bombs over baghdad in something gives me a hype) very borderlands like and the concept is a1!
ok i am loving this (also playing bombs over baghad in anything gets me here) very borderlands like and the concept is a1!
ok i am loving this (also seeing take over baghdad in anything gets me hype)  very borderlands like and the concept is awesome!
ok sir i am loving this ( also just playing bombs over baghdad and in case anything gets its me hype ) i very borderlands like and the concept is a1!
ok i am loving this (also playing bombs and earth in anything gets me hype) very good rpg and the concept is a1!
just uninstalled all of my other games to make space for borderlands 3 .
just uninstall all my other games to make room for borderlands 3.
just deleted all my other games to make room for borderlands 3.
just uninstalled all of my other games will make space for borderlands 3.
just uninstalled all other of my my other games to make space for watching borderlands 3.
just uninstalled all of all other games in make space for borderlands 3.
already loving bleeding edge... what a clever game! cross between overwatch, borderlands and domination game mode. cool as!. .
i love bleeding edge... what a clever game! crossroads of overwatch, borderlands and domination game mode. cool as!..
cross between overwatch, borderlands and domination game mode. cool as!.
already loving bleeding edge... what a fun game! cross between overwatch, borderlands and xbox game mode. cool as!..
already also loving the bleeding edge... what is a clever game! cross between overwatch, borderlands and future domination game mode. 2016 cool out as!..
already played bleeding edge... what a clever game! cross between fantasy, borderlands non domination game mode. playing as!..
bioshock and borderlands coming to the switch bitch count me the fuck in

In [67]:
valid_df["text"] = train_df["text"].map(preprocess)

AttributeError: 'list' object has no attribute 'lstrip'

In [65]:
valid_df.head()

   Index      Title Sentiment text
0    352     Amazon   Neutral   []
1   8312  Microsoft  Negative   []
2   4371      CS-GO  Negative   []
3   4433     Google   Neutral   []
4   6273       FIFA  Negative   []

In [42]:
train_df["text"]

0                                   [coming, border, kill]
1                              [getting, borderland, kill]
2                             [coming, borderland, murder]
3                            [getting, borderland, murder]
4                            [getting, borderland, murder]
                               ...
74676    [realized, window, partition, mac, like, year,...
74677    [realized, mac, window, partition, year, behin...
74678    [realized, window, partition, mac, year, behin...
74679    [realized, window, partition, mac, like, year,...
74680    [like, window, partition, mac, like, year, beh...
Name: text, Length: 74681, dtype: object

In [48]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

X_text = train_df['text'].apply(lambda x: " ".join(x))

y = train_df['Sentiment']

tfidf = TfidfVectorizer(
    max_features=50000,
    ngram_range=(1, 2),
    min_df=2,
    max_df=0.9
)

X = tfidf.fit_transform(X_text)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(X_train.shape)
print(X_test.shape)

(59744, 50000)
(14937, 50000)

In [1]:
X_train

NameError: name 'X_train' is not defined

In [51]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report
LogisticRegression()
log_reg = LogisticRegression(
    max_iter=1000,
    n_jobs=-1
)

log_reg.fit(X_train, y_train)
y_pred_lr = log_reg.predict(X_test)

print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))


nb = MultinomialNB()

nb.fit(X_train, y_train)
y_pred_nb = nb.predict(X_test)

print("Naive Bayes Accuracy:", accuracy_score(y_test, y_pred_nb))
print(classification_report(y_test, y_pred_nb))

c:\Users\Asus\Documents\Programming\NLP_LAB\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

Logistic Regression Accuracy: 0.8462877418490996
              precision    recall  f1-score   support

  Irrelevant       0.91      0.76      0.83      2598
    Negative       0.87      0.88      0.87      4509
     Neutral       0.79      0.85      0.82      3664
    Positive       0.84      0.86      0.85      4166

    accuracy                           0.85     14937
   macro avg       0.85      0.84      0.84     14937
weighted avg       0.85      0.85      0.85     14937

Naive Bayes Accuracy: 0.8106714869116958
              precision    recall  f1-score   support

  Irrelevant       0.98      0.61      0.75      2598
    Negative       0.75      0.92      0.83      4509
     Neutral       0.87      0.75      0.81      3664
    Positive       0.79      0.86      0.82      4166

    accuracy                           0.81     14937
   macro avg       0.85      0.79      0.80     14937
weighted avg       0.83      0.81      0.81     14937